# ASP.NET Core
# Build and test ASp.NET Core projects targeting .NET Core.
# Add steps that build, run tests, create a NuGet package deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration'
